"""
Pydantic models for the Deep Research module.
"""
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ResearchPhase(str, Enum):
    """Phases of the research pipeline."""
    PLANNING = "planning"
    RESEARCHING = "researching"
    COMPRESSING = "compressing"
    FOLLOW_UP = "follow_up"
    WRITING = "writing"
    DONE = "done"


class ThinkDecision(str, Enum):
    """Decision outcomes from the think tool."""
    CONTINUE_RESEARCH = "continue_research"
    SUFFICIENT_DATA = "sufficient_data"
    NEED_DIFFERENT_ANGLE = "need_different_angle"


class SubQuestion(BaseModel):
    """A sub-question generated by the research planner."""
    question: str = Field(..., description="The specific research question")
    search_queries: List[str] = Field(
        default_factory=list,
        description="Suggested search queries for this question"
    )
    priority: int = Field(default=1, ge=1, le=5, description="Priority 1-5 (1 is highest)")
    rationale: Optional[str] = Field(None, description="Why this question matters")


class ResearchOutline(BaseModel):
    """Research plan created by the planner."""
    main_question: str = Field(..., description="The original user query")
    sub_questions: List[SubQuestion] = Field(
        default_factory=list,
        description="Breakdown into specific sub-questions"
    )
    research_strategy: str = Field(
        default="",
        description="High-level approach to answering the question"
    )
    expected_sources: List[str] = Field(
        default_factory=list,
        description="Types of sources expected (web, SEC filings, news, etc.)"
    )


class SourceNote(BaseModel):
    """A note extracted from a single source."""
    source_url: str = Field(..., description="URL of the source")
    source_title: str = Field(..., description="Title of the source")
    source_type: str = Field(default="web", description="Type: web, news, sec, pdf")
    content_summary: str = Field(..., description="Summary of relevant content")
    key_facts: List[str] = Field(
        default_factory=list,
        description="Key facts extracted from this source"
    )
    relevance_score: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="How relevant this source is to the question"
    )
    extracted_at: datetime = Field(default_factory=datetime.utcnow)
    research_question: str = Field(default="", description="The question this addresses")


class ThinkResult(BaseModel):
    """Result from the think tool checkpoint."""
    thought: str = Field(..., description="The reasoning/reflection")
    decision: ThinkDecision = Field(..., description="What to do next")
    next_query: Optional[str] = Field(None, description="Next search query if continuing")
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in having sufficient data"
    )


class ResearchUnitResult(BaseModel):
    """Result from a single research unit execution."""
    sub_question: str = Field(..., description="The question that was researched")
    notes: List[SourceNote] = Field(
        default_factory=list,
        description="Notes gathered from sources"
    )
    iterations: int = Field(default=0, description="Number of LLM iterations used")
    completed: bool = Field(default=False, description="Whether research completed normally")
    error: Optional[str] = Field(None, description="Error message if failed")
    tool_calls_made: int = Field(default=0, description="Total tool calls in this unit")


class CompressedFindings(BaseModel):
    """Consolidated findings from all research units."""
    main_question: str = Field(..., description="The original user query")
    key_findings: List[str] = Field(
        default_factory=list,
        description="Consolidated key findings"
    )
    supporting_evidence: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Evidence with source citations"
    )
    gaps_identified: List[str] = Field(
        default_factory=list,
        description="Information gaps that couldn't be filled"
    )
    source_summary: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Summary of all sources used"
    )
    total_sources: int = Field(default=0, description="Total unique sources used")


class ResearchState(BaseModel):
    """Complete state of a research session."""
    conversation_id: str = Field(..., description="Parent conversation ID")
    query: str = Field(..., description="Original user query")
    phase: ResearchPhase = Field(default=ResearchPhase.PLANNING)
    outline: Optional[ResearchOutline] = None
    unit_results: List[ResearchUnitResult] = Field(default_factory=list)
    compressed_findings: Optional[CompressedFindings] = None
    final_report: str = Field(default="", description="The final markdown report")

    # Statistics
    total_sources: int = Field(default=0)
    total_tool_calls: int = Field(default=0)
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None

    # All references for citations
    all_references: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="All unique sources with citation numbers"
    )


class ResearchProgressEvent(BaseModel):
    """Event for streaming research progress."""
    type: str = Field(default="research_progress")
    phase: ResearchPhase
    unit_index: Optional[int] = None
    total_units: Optional[int] = None
    unit_status: Optional[str] = None
    sources_found: Optional[int] = None
    message: Optional[str] = None
